// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChGIVGmVRNlak9vJ9xYtT9a1mqKxG6URw',
    appId: '1:739620214432:web:7e3ec079f438ff3e405bc5',
    messagingSenderId: '739620214432',
    projectId: 'roomzyfind-5a8af',
    authDomain: 'roomzyfind-5a8af.firebaseapp.com',
    databaseURL: 'https://roomzyfind-5a8af-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'roomzyfind-5a8af.firebasestorage.app',
    measurementId: 'G-13SM3E3ZW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3JpD67T2rD9QhVaDHTbFuXP1lmZ4Ab94',
    appId: '1:739620214432:android:74ff7b43c297dd94405bc5',
    messagingSenderId: '739620214432',
    projectId: 'roomzyfind-5a8af',
    databaseURL: 'https://roomzyfind-5a8af-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'roomzyfind-5a8af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_0ZInn5dh6LRHY3tzJug1gOiSJG2fXUw',
    appId: '1:739620214432:ios:f1ace0f93ca2e2ab405bc5',
    messagingSenderId: '739620214432',
    projectId: 'roomzyfind-5a8af',
    databaseURL: 'https://roomzyfind-5a8af-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'roomzyfind-5a8af.firebasestorage.app',
    iosBundleId: 'com.example.roomzyNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_0ZInn5dh6LRHY3tzJug1gOiSJG2fXUw',
    appId: '1:739620214432:ios:f1ace0f93ca2e2ab405bc5',
    messagingSenderId: '739620214432',
    projectId: 'roomzyfind-5a8af',
    databaseURL: 'https://roomzyfind-5a8af-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'roomzyfind-5a8af.firebasestorage.app',
    iosBundleId: 'com.example.roomzyNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChGIVGmVRNlak9vJ9xYtT9a1mqKxG6URw',
    appId: '1:739620214432:web:49460195278d2eac405bc5',
    messagingSenderId: '739620214432',
    projectId: 'roomzyfind-5a8af',
    authDomain: 'roomzyfind-5a8af.firebaseapp.com',
    databaseURL: 'https://roomzyfind-5a8af-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'roomzyfind-5a8af.firebasestorage.app',
    measurementId: 'G-767XN2VKLC',
  );
}
